### ISSUE TITLE
Popup to add book

### ISSUE THREAD

**Issue by mia-jane** [mia-jane/book-list#2]
### Tasks

- [x] set max width of the popup
- [x] put complete border around summary input field
- [x] add padding to the top of the form
- [x] move x btn to the right of the popup
- [x] put space between the x button and the form itself
